eureka:
  client:
    enabled: false

info:
  build:
    version: @project.version@

security:
  basic:
    enabled: false

zuul:
  add-proxy-headers: true
  ignored-services: "*"
  routes:
    employees:
      serviceId: employees

